# -*- coding: utf-8 -*-
"""Копия блокнота "PythonUrban_lab2.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGGS0g3d_vD30epFSvjZ5daabPgaNpGg

# Итоговый проект. Улицы. Объекты культурного наследия.
"""

!pip install geopandas
!pip install osmnx

import geopandas as gpd
import osmnx as ox

TILES = "CartoDB positron"  # Название подложки для карт

TERRITORY_NAME = "Пушкинский район, Санкт-Петербург"  # название территории для которой будут строиться слои

KGIOP_FILE_URL = "https://raw.githubusercontent.com/NordWitch/PythonUrbanITMO_NW/main/geojson%20%D1%81%D0%BB%D0%BE%D0%B8/kgiop_objects.geojson"  # ссылка на слой с объектами культурного наследия
STREETS_FILE_URL = "https://raw.githubusercontent.com/NordWitch/PythonUrbanITMO_NW/main/geojson%20%D1%81%D0%BB%D0%BE%D0%B8/streets.geojson"  # ссылка на слой с улицами

"""## Территория

### Загрузка территории из OSM (Extract)
"""

district = ox.geocode_to_gdf(TERRITORY_NAME)
district

"""## Улицы

### Загрузка файла с улицами (Extract)
"""

streets_gdf = gpd.read_file(STREETS_FILE_URL,mask=district)

streets_gdf

"""### Обработка данных с улицами (Transform)"""

if not streets_gdf["name"].is_unique:
  streets_gdf = streets_gdf.dissolve(by="name")
streets_gdf

"""### Сохранение слоя с улицами (Load)"""

streets_gdf.index.rename("Название",inplace=True)
streets_gdf

streets_gdf.to_crs(4326).to_file('district_streets.geojson', driver='GeoJSON')

"""## Объекты культурного наследия

### Загрузка объектов культурного наследия (Extract)
"""

sights_gdf = gpd.read_file(KGIOP_FILE_URL,mask=district)

sights_gdf

"""### Обработка объектов культурного наследия (Transform)"""

sights_gdf["lon"] = sights_gdf.to_crs(3857).geometry.centroid.to_crs(4326).x
sights_gdf["lat"] = sights_gdf.to_crs(3857).geometry.centroid.to_crs(4326).y
sights_gdf

"""### Сохранение слоя с объектами культурного наследия (Load)"""

# TODO переименовать столбцы в русские названия, кроме столбца geometry
sights_gdf.rename(columns = {"id" : "Идентификатор", "ensemble_name" : "Ансамбль", "object_name" : "Объект", "occurrence_time" : "Год","object_location" : "Местоположение","historical_category" : "Категория","normative_act" : "Документ","object_type" : "Тип","lon" : "Долгота","lat" : "Широта"}, inplace = True)
sights_gdf

sights_gdf.to_crs(4326).to_file('sights.geojson', driver='GeoJSON')